### PR TITLE
update language files of zh-cn

### PR DESCRIPTION
**Pull request by lisposter**
I have updated language files of zh-cn, pls review.

### CODE REVIEW

**Comment by rvagg** [comment]
would if I could! looks impressive

**Comment by rvagg** [comment]
adding you as collaborator @lisposter, ping me in here when you're satisfied that this is ready to go and I'll push a release

**Comment by lisposter** [comment]
@rvagg Thanks,  I  will do more tests for it, and I will update the language files of  `learnyounode` soon. I will ping you when they are all looks good.

**Comment by lisposter** [comment]
@rvagg  It's LGTM. I think it's ready to go now.

**Comment by rvagg** [comment]
k, you have collaborator status on here and in workshopper-exercise, you can merge both when you're ready and I'll bump patch level and release both

**Comment by rvagg** [comment]
actually a minor version bump for the 3 modules, including learnyounode, to signify zh-cn support might be good, are all 3 ready to go or are these changes just limited to workshopper* at the moment?

**Comment by lisposter** [comment]
@rvagg I am working on `learnyounode` now, it will be ready soon.

**Pull request merged**
