### PR TITLE
L10n fr: completed language names… across language names + i18n example leg-up

### PR DESCRIPTION
**Pull request by tdd**
Hey guys,

Sorry I put this unabashedly in `master` earlier instead of doing a PR, here goes the proper approach, as per #89.

There are two sets here:

* `examples/i18n` directory (that `examples`dir should really be `example` at this point, or a subdir of `examples`, btw), so contributors can better visualize how to test their language contributions in an actual workshopper.
* Updates to all language files in `i18n` so they all contain all currently available languages.

### CODE REVIEW

**Comment by martinheidegger** [comment]
Very nice, thanks!

**Comment by rvagg** [comment]
how about we go with standard `JSON.stringify(obj, null, 2)` formatting for all of these json files? I have the i18n changes in #90 which I'll rebase after this lands, but how about you do the ones in examples/i18n/ in your PR before landing this.

I'm guessing there won't be any objections so land when you're ready.

**Comment by tdd** [comment]
Hey!

I applied your one-line from #90 to all JSON files in `i18n` and `examples/i18n`, as requested (so your `jsonify` branch and #90 can be closed as dups, I guess).

Also, and this is the one reason I'm not merging right now: I figured it would be nice to follow the pr-br example and add an English-language " (CHOOSE LANGUAGE)" suffix to all translated items for it, so users stuck with a local language def they don't understand can find that menu item more easily.

Sounds good to you? Ready for merge?

**Comment by rvagg** [comment]
up to you, merge if you're happy with it as is and I'll probably patch-bump this one unless you see a reason for this to be minor.

**Comment by tdd** [comment]
Merging. Patch-level sounds fine.

**Comment by rvagg** [comment]
v2.3.1 great work!

**Pull request merged**
