### PR TITLE
Added Vietnamese

### PR DESCRIPTION
**Pull request by dominhhai**
Prepare for translating all workshops to Vietnamese.

### CODE REVIEW

**Comment by martinheidegger** [comment]
LGTM

**Comment by ralphtheninja** [comment]
:+1:

**Comment by martinheidegger** [comment]
@dominhhai Do you have someone to check-read it?

**Comment by dominhhai** [comment]
We are checking the translated workshop on Windows and Linux platform.

**Comment by martinheidegger** [comment]
@dominhhai I meant: is there another person that reads through the translation. Since you wrote "we" I am assuming yes. It would be good to add the names to the contributors readme.

**Comment by dominhhai** [comment]
Thanks for your helping!  We have a group of three people, translate and check on some OS platforms. I will add the names to the contributors.

**Comment by dominhhai** [comment]
@martinheidegger  Can you merge this PR?

**Comment by dominhhai** [comment]
:100: Thank you very much!

**Pull request merged**
