### PR TITLE
More spanish words

### PR DESCRIPTION
**Pull request by cronopio**
Hi
Added more words to the spanish translation.
Please another spanish reader review and check the words and if have meaning for Spain and Latinos.
I'm latino but I guess the words used should work for europeans, let me know.

Cheers!

### CODE REVIEW

**Comment by cronopio** [comment]
Fixed

**Comment by ralphtheninja** [comment]
Ready for merge? Give me some thumbs up please! :)

**Comment by cronopio** [comment]
@xfry @montogeek Ready to merge, right? Write a +1!

:+1:

**Comment by montogeek** [comment]
https://heavyeditorial.files.wordpress.com/2012/09/chuck-norris-approves.gif?w=780

**Comment by ralphtheninja** [comment]
lol

**Comment by ralphtheninja** [comment]
Awesome work. Gracias!

**Comment by cronopio** [comment]
@ralphtheninja Thank you!

**Pull request merged**
